globs:
  - "concepts/**/*.md"
  - "exercises/concept/**/*.md"

config:
  MD001: true
  MD002: true
  MD003: 
    style: "atx"
  MD004: 
    style: dash
  MD013: false
  MD033: false

customRules: 
  - "single-sentence-per-line-rule.js"